
author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.55
license: perl
name: Rubric-Entry-Formatter-Markdown
no_index: 
  directory: 
    - inc
    - t
requires: 
  Rubric: 0.1302
  Text::Markdown: 1.0.3
version: 0.01
