--- 
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Rubric-Entry-Formatter-Markdown
no_index: 
  directory: 
    - inc
    - t
requires: 
  Rubric: 0.1302
  Text::Markdown: 1.0.3
tests: t/*.t xt/*.t
version: 0.553
